[theme]
primaryColor = "#1f77b4"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"

[server]
headless = false
runOnSave = true
maxUploadSize = 5

[browser]
gatherUsageStats = false
